// examples/solid-example/src/routes/rpc-mutation.tsx
import { useMutation } from "@tanstack/solid-query";
import { Cause, Effect } from "effect";
import { createSignal, Show } from "solid-js";
import { ExampleRpcClient, rpcEq } from "../lib/effect-rpc-example";

export default function RpcMutation() {
  const [errorMessage, setErrorMessage] = createSignal("");

  const mutation = useMutation(() =>
    rpcEq.mutationOptions({
      mutationFn: (variables: { id: string; name: string }) =>
        Effect.gen(function* () {
          const rpcClient = yield* ExampleRpcClient;
          return yield* rpcClient.RenameUser(variables);
        }),
      mutationKey: ["rpc", "rename-user"],
      onError: (error) =>
        setErrorMessage(
          error.match({
            OrElse: (cause) => `Error renaming user: ${Cause.pretty(cause)}`,
            RenameUserError: (renameUserError) => renameUserError.message,
          })
        ),
      onMutate: () => setErrorMessage(""),
    })
  );

  return (
    <div>
      <p>Uses the same Effect RPC client inside a mutation.</p>
      <button
        onClick={() => mutation.mutate({ id: "user-123", name: "Ripley" })}
        type="button"
      >
        Rename to Ripley
      </button>
      <button
        onClick={() => mutation.mutate({ id: "user-123", name: "HAL" })}
        type="button"
      >
        Rename to HAL
      </button>
      <Show when={mutation.isPending}>
        <div>Updating...</div>
      </Show>
      <Show when={mutation.data}>{(data) => <div>{data()}</div>}</Show>
      <Show when={errorMessage()}>
        <div>{errorMessage()}</div>
      </Show>
    </div>
  );
}

// examples/svelte-example/src/routes/RpcMutation.svelte
<script lang="ts">
  import { createMutation } from "@tanstack/svelte-query";
  import { Cause, Effect } from "effect";
  import { ExampleRpcClient, rpcEq } from "../lib/effect-rpc-example";

  let errorMessage = $state("");

  const mutation = createMutation(() =>
    rpcEq.mutationOptions({
      mutationFn: (variables: { id: string; name: string }) =>
        Effect.gen(function* () {
          const rpcClient = yield* ExampleRpcClient;
          return yield* rpcClient.RenameUser(variables);
        }),
      mutationKey: ["rpc", "rename-user"],
      onError: (error) => {
        errorMessage = error.match({
          OrElse: (cause) => `Error renaming user: ${Cause.pretty(cause)}`,
          RenameUserError: (renameUserError) => renameUserError.message,
        });
      },
      onMutate: () => {
        errorMessage = "";
      },
    })
  );
</script>

<div>
  <p>Uses the same Effect RPC client inside a mutation.</p>
  <button
    onclick={() => mutation.mutate({ id: "user-123", name: "Ripley" })}
    type="button"
  >
    Rename to Ripley
  </button>
  <button
    onclick={() => mutation.mutate({ id: "user-123", name: "HAL" })}
    type="button"
  >
    Rename to HAL
  </button>
  {#if mutation.isPending}
    <div>Updating...</div>
  {:else if mutation.isSuccess}
    <div>{mutation.data}</div>
  {/if}
  {#if errorMessage}
    <div>{errorMessage}</div>
  {/if}
</div>
