// examples/react-example/app/routes/examples/rpc/rpc-query.tsx
import { useQuery } from "@tanstack/react-query";
import { Effect } from "effect";
import { ExampleRpcClient, rpcEq } from "~/lib/effect-rpc-example";

const greetingName = "Voyager";

const greetingQueryOptions = rpcEq.queryOptions({
  queryKey: ["rpc", "get-greeting", greetingName],
  queryFn: () =>
    Effect.gen(function* () {
      const rpcClient = yield* ExampleRpcClient;
      return yield* rpcClient.GetGreeting({
        name: greetingName,
      });
    }),
});

export default function RpcQueryRoute() {
  const { data, status } = useQuery(greetingQueryOptions);

  return (
    <div>
      <p>
        Uses an Effect RPC client backed by a local `RpcGroup` through
        `RpcTest.makeClient`.
      </p>
      {status === "pending" && <div>Loading...</div>}
      {status === "success" && <div>{data}</div>}
    </div>
  );
}

// examples/solid-example/src/routes/rpc-query.tsx
import { useQuery } from "@tanstack/solid-query";
import { Effect } from "effect";
import { Show } from "solid-js";
import { ExampleRpcClient, rpcEq } from "../lib/effect-rpc-example";

const greetingName = "Voyager";

const greetingQueryOptions = rpcEq.queryOptions({
  queryFn: () =>
    Effect.gen(function* () {
      const rpcClient = yield* ExampleRpcClient;
      return yield* rpcClient.GetGreeting({ name: greetingName });
    }),
  queryKey: ["rpc", "get-greeting", greetingName],
});

export default function RpcQuery() {
  const query = useQuery(() => greetingQueryOptions);

  return (
    <div>
      <p>
        Uses an Effect RPC client backed by a local `RpcGroup` through
        `RpcTest.makeClient`.
      </p>
      <Show fallback={<div>Loading...</div>} when={query.data}>
        {(data) => <div>{data()}</div>}
      </Show>
    </div>
  );
}
