// examples/svelte-example/src/routes/RpcMutation.svelte
<script lang="ts">
  import { createMutation } from "@tanstack/svelte-query";
  import { Cause, Effect } from "effect";
  import { ExampleRpcClient, rpcEq } from "../lib/effect-rpc-example";

  let errorMessage = $state("");

  const mutation = createMutation(() =>
    rpcEq.mutationOptions({
      mutationFn: (variables: { id: string; name: string }) =>
        Effect.gen(function* () {
          const rpcClient = yield* ExampleRpcClient;
          return yield* rpcClient.RenameUser(variables);
        }),
      mutationKey: ["rpc", "rename-user"],
      onError: (error) => {
        errorMessage = error.match({
          OrElse: (cause) => `Error renaming user: ${Cause.pretty(cause)}`,
          RenameUserError: (renameUserError) => renameUserError.message,
        });
      },
      onMutate: () => {
        errorMessage = "";
      },
    })
  );
</script>

<div>
  <p>Uses the same Effect RPC client inside a mutation.</p>
  <button
    onclick={() => mutation.mutate({ id: "user-123", name: "Ripley" })}
    type="button"
  >
    Rename to Ripley
  </button>
  <button
    onclick={() => mutation.mutate({ id: "user-123", name: "HAL" })}
    type="button"
  >
    Rename to HAL
  </button>
  {#if mutation.isPending}
    <div>Updating...</div>
  {:else if mutation.isSuccess}
    <div>{mutation.data}</div>
  {/if}
  {#if errorMessage}
    <div>{errorMessage}</div>
  {/if}
</div>

// examples/vue-example/src/views/RpcMutation.vue
<script setup lang="ts">
import { useMutation } from "@tanstack/vue-query";
import { Cause, Effect } from "effect";
import { ref } from "vue";
import { ExampleRpcClient, rpcEq } from "../lib/effect-rpc-example";

const errorMessage = ref("");

const { data, mutate, status } = useMutation(
  rpcEq.mutationOptions({
    mutationFn: (variables: { id: string; name: string }) =>
      Effect.gen(function* () {
        const rpcClient = yield* ExampleRpcClient;
        return yield* rpcClient.RenameUser(variables);
      }),
    mutationKey: ["rpc", "rename-user"],
    onError: (error) => {
      errorMessage.value = error.match({
        OrElse: (cause) => `Error renaming user: ${Cause.pretty(cause)}`,
        RenameUserError: (renameUserError) => renameUserError.message,
      });
    },
    onMutate: () => {
      errorMessage.value = "";
    },
  })
);
</script>

<template>
  <div>
    <p>Uses the same Effect RPC client inside a mutation.</p>
    <button type="button" @click="mutate({ id: 'user-123', name: 'Ripley' })">
      Rename to Ripley
    </button>
    <button type="button" @click="mutate({ id: 'user-123', name: 'HAL' })">
      Rename to HAL
    </button>
    <div v-if="status === 'pending'">Updating...</div>
    <div v-else-if="status === 'success'">{{ data }}</div>
    <div v-if="errorMessage">{{ errorMessage }}</div>
  </div>
</template>
